// ════════════════════════════════════════════════════════
// KANOOR VILLAGE MAP — Seed Place Data
// Built by Hakima Banoo
// ════════════════════════════════════════════════════════

module.exports = [
  {id:"p1",name:"Zambakha Mohalla",category:"mohalla",icon:"🏘️",lat:34.3158,lng:76.0078,description:"One of the lower mohallas of Kanoor village. Home to Primary School Zambakha and Masjid Zambakha. Among the oldest settlements.",mohalla:"Zambakha"},
  {id:"p2",name:"Saserpo Mohalla",category:"mohalla",icon:"🏘️",lat:34.3140,lng:76.0102,description:"Central mohalla housing the vital Sub Medical Health Centre. Key residential area of Kanoor.",mohalla:"Saserpo"},
  {id:"p3",name:"Yougma Yourgo Mohalla",category:"mohalla",icon:"🏘️",lat:34.3122,lng:76.0128,description:"Upper Yourgo — one of the largest mohallas in Kanoor. Site of Middle School Yourgo.",mohalla:"Yougma Yourgo"},
  {id:"p4",name:"Gongma Yourgo Mohalla",category:"mohalla",icon:"🏘️",lat:34.3108,lng:76.0142,description:"Lower Yourgo mohalla, at the centre of Kanoor village along the main road.",mohalla:"Gongma Yourgo"},
  {id:"p5",name:"Grong Mohalla",category:"mohalla",icon:"🏘️",lat:34.3092,lng:76.0158,description:"Prominent mohalla of Kanoor with its own masjid and strong community presence.",mohalla:"Grong"},
  {id:"p6",name:"Bargong Mohalla",category:"mohalla",icon:"🏘️",lat:34.3072,lng:76.0178,description:"Bargong is the administrative heart of Kanoor — home to the Gram Panchayat Office.",mohalla:"Bargong"},
  {id:"p7",name:"Saltong Mohalla",category:"mohalla",icon:"🏘️",lat:34.3188,lng:76.0068,description:"Scenic upper mohalla known for Primary School Saltong, the Rkong waterfall, and the village picnic spot.",mohalla:"Saltong"},
  {id:"p8",name:"Scarchey Mohalla",category:"mohalla",icon:"🏘️",lat:34.3145,lng:76.0093,description:"Home to the Children's Park and Ahuna Resort, popular with visitors to the Suru Valley.",mohalla:"Scarchey"},
  {id:"p9",name:"Chanigund Mohalla",category:"mohalla",icon:"🏘️",lat:34.3178,lng:76.0052,description:"Residential mohalla in the upper part of Kanoor village.",mohalla:"Chanigund"},
  {id:"p10",name:"Gongma Kanoor Mohalla",category:"mohalla",icon:"🏘️",lat:34.3062,lng:76.0195,description:"Lower Kanoor area, one of the southernmost mohallas of the village.",mohalla:"Gongma Kanoor"},
  {id:"p11",name:"Zanging Mohalla",category:"mohalla",icon:"🏘️",lat:34.3095,lng:76.0155,description:"Zanging area of Kanoor, home to Middle School Zanging.",mohalla:"Zanging"},
  {id:"p20",name:"Kanoor Main Bridge",category:"bridge",icon:"🌉",lat:34.3132,lng:76.0112,description:"Primary bridge of Kanoor over the Suru River. Vital crossing connecting the village to the Suru Valley road network.",mohalla:"Main Road"},
  {id:"p21",name:"Kanoor–Trespone Bridge",category:"bridge",icon:"🌉",lat:34.3148,lng:76.0088,description:"Connects Kanoor to Trespone (Gm Pora), the Block Panchayat headquarters.",mohalla:"North End"},
  {id:"p22",name:"Kanoor–Tambis Bridge",category:"bridge",icon:"🌉",lat:34.3115,lng:76.0138,description:"Bridge linking Kanoor to the neighbouring village of Tambis across the Suru River.",mohalla:"Central"},
  {id:"p30",name:"Middle School Yourgo",category:"school",icon:"🏫",lat:34.3120,lng:76.0130,description:"Government middle school serving students of the Yourgo area. Main educational institution of Kanoor village.",mohalla:"Yougma Yourgo"},
  {id:"p31",name:"Middle School Zanging",category:"school",icon:"🏫",lat:34.3095,lng:76.0152,description:"Government middle school in Zanging locality catering to students from multiple mohallas.",mohalla:"Zanging"},
  {id:"p32",name:"Primary School Zambakha",category:"school",icon:"🏫",lat:34.3160,lng:76.0075,description:"Primary school providing foundational education to children of Zambakha mohalla.",mohalla:"Zambakha"},
  {id:"p33",name:"Primary School Saltong",category:"school",icon:"🏫",lat:34.3185,lng:76.0070,description:"Primary school serving the children of Saltong and surrounding upper mohallas.",mohalla:"Saltong"},
  {id:"p40",name:"Sub Medical Health Centre",category:"health",icon:"🏥",lat:34.3138,lng:76.0106,description:"Primary healthcare facility for Kanoor and surrounding villages. Provides essential medical services to the entire Suru Valley area.",mohalla:"Saserpo"},
  {id:"p50",name:"Kanoor Imambargah",category:"imambargah",icon:"🏛️",lat:34.3128,lng:76.0118,description:"Main Imambargah of Kanoor village — central place of religious gathering, Muharram observances and community meetings.",mohalla:"Central"},
  {id:"p60",name:"Masjid Zambakha",category:"mosque",icon:"🕌",lat:34.3162,lng:76.0074,description:"Neighbourhood mosque of Zambakha mohalla for daily prayers and religious gatherings.",mohalla:"Zambakha"},
  {id:"p61",name:"Masjid Saserpo",category:"mosque",icon:"🕌",lat:34.3137,lng:76.0110,description:"Mosque of Saserpo mohalla, centrally located for the convenience of residents.",mohalla:"Saserpo"},
  {id:"p62",name:"Masjid Yourgo",category:"mosque",icon:"🕌",lat:34.3116,lng:76.0133,description:"Central mosque for the Yourgo area serving both upper and lower Yourgo mohallas.",mohalla:"Yourgo"},
  {id:"p63",name:"Masjid Grong",category:"mosque",icon:"🕌",lat:34.3090,lng:76.0162,description:"Mosque of Grong mohalla — important place of worship for Grong and Bargong communities.",mohalla:"Grong"},
  {id:"p64",name:"Masjid Bargong",category:"mosque",icon:"🕌",lat:34.3074,lng:76.0176,description:"Mosque of Bargong mohalla, situated near the Panchayat Office.",mohalla:"Bargong"},
  {id:"p65",name:"Masjid Saltong",category:"mosque",icon:"🕌",lat:34.3189,lng:76.0066,description:"Mosque serving the Saltong area community in the upper reaches of Kanoor village.",mohalla:"Saltong"},
  {id:"p66",name:"Masjid Scarchey",category:"mosque",icon:"🕌",lat:34.3148,lng:76.0090,description:"Mosque in Scarchey area, serving residents near the Children's Park and Ahuna Resort.",mohalla:"Scarchey"},
  {id:"p67",name:"Masjid Chanigund",category:"mosque",icon:"🕌",lat:34.3180,lng:76.0048,description:"Local mosque for Chanigund mohalla residents.",mohalla:"Chanigund"},
  {id:"p68",name:"Masjid Zanging",category:"mosque",icon:"🕌",lat:34.3093,lng:76.0158,description:"Mosque serving the Zanging and Gongma Yourgo area residents.",mohalla:"Zanging"},
  {id:"p70",name:"Rkong Saltong Waterfall",category:"nature",icon:"🌊",lat:34.3198,lng:76.0055,description:"A stunning natural waterfall in the Rkong area of Saltong — one of the most beautiful scenic spots in the Suru Valley and a hidden gem of Kargil.",mohalla:"Saltong"},
  {id:"p71",name:"Saltong Picnic Spot",category:"nature",icon:"🌿",lat:34.3192,lng:76.0060,description:"A beloved picnic spot in Saltong offering breathtaking views of the Suru Valley mountains. Popular with families and visitors.",mohalla:"Saltong"},
  {id:"p72",name:"Suru River View Point",category:"nature",icon:"🏞️",lat:34.3130,lng:76.0085,description:"Scenic vantage point along the Suru River with panoramic views of the river valley and surrounding high-altitude mountains.",mohalla:"Central"},
  {id:"p80",name:"Children's Park, Scarchey",category:"park",icon:"🌿",lat:34.3143,lng:76.0096,description:"Beloved children's park in Scarchey, opposite the Ahuna Resort. Main recreational space for children of Kanoor village.",mohalla:"Scarchey"},
  {id:"p81",name:"Ahuna Resort",category:"resort",icon:"🏡",lat:34.3141,lng:76.0100,description:"Scenic resort in Scarchey area, welcoming visitors to the pristine Suru Valley.",mohalla:"Scarchey"},
  {id:"p90",name:"Kanoor Gram Panchayat Office",category:"govt",icon:"🏛️",lat:34.3073,lng:76.0180,description:"Official Gram Panchayat Office of Kanoor village in Bargong mohalla. Handles village governance, public records and administrative matters.",mohalla:"Bargong"},
  {id:"p91",name:"Kanoor Bus Stop",category:"govt",icon:"🚌",lat:34.3129,lng:76.0115,description:"Main bus stop of Kanoor village on the Sankoo–Panikhar route.",mohalla:"Central"},
  {id:"p100",name:"Chicken & Meat Shop",category:"shop",icon:"🛍️",lat:34.3127,lng:76.0119,description:"Popular poultry and meat shop on the main road of Kanoor, serving residents of all mohallas.",mohalla:"Main Road"},
  {id:"p101",name:"General Stores Row",category:"shop",icon:"🛍️",lat:34.3130,lng:76.0116,description:"Cluster of general provision and grocery stores along the main road.",mohalla:"Main Road"},
  {id:"p102",name:"Pharmacy / Medical Store",category:"shop",icon:"💊",lat:34.3136,lng:76.0108,description:"Medical and pharmaceutical store near the Health Centre in Saserpo.",mohalla:"Saserpo"},
];
